# Generated by Django 3.2.25 on 2026-04-01 10:53

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatNotification',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('notification_id', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('recipient_id', models.IntegerField()),
                ('sender_id', models.IntegerField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('message', 'New Message'), ('mention', 'Mention'), ('reaction', 'Reaction')], max_length=20)),
                ('message_obj_id', models.IntegerField(blank=True, null=True)),
                ('chat_room_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('room_id', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('room_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chat_rooms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('message_id', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('chat_room_id', models.IntegerField()),
                ('sender_id', models.IntegerField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('replied_to_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('status_id', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('user_id', models.IntegerField(unique=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_status',
            },
        ),
        migrations.CreateModel(
            name='MessageReadReceipt',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('receipt_id', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('message_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'message_read_receipts',
                'unique_together': {('message_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='ChatRoomParticipant',
            fields=[
                ('room_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('participant_id', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('chat_room_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_room_participants',
                'unique_together': {('chat_room_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('block_id', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('user_id', models.IntegerField()),
                ('blocked_user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blocked_users',
                'unique_together': {('user_id', 'blocked_user_id')},
            },
        ),
    ]
