# Generated by Django 3.2.25 on 2026-04-27 13:13

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patientprofile_patient_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='assigned_ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='available_days',
            field=djongo.models.fields.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='available_time',
            field=djongo.models.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='documents',
            field=djongo.models.fields.JSONField(blank=True, default=dict, help_text='Store all documents in one JSON field:\n    {\n        "medical_degree": "file_path_or_url",\n        "md_ms_certificate": "file_path_or_url",\n        "medical_license": "file_path_or_url",\n        "id_proof": "file_path_or_url",\n        "address_proof": "file_path_or_url",\n        "experience_letter": "file_path_or_url",\n        "specialization_certificates": ["file1.pdf", "file2.pdf"],\n        "research_papers": ["paper1.pdf", "paper2.pdf"],\n        "other_documents": ["file1.jpg", "file2.pdf"]\n    }\n    '),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='employment_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='shift',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='skills',
            field=djongo.models.fields.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='supervisor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='uploaded_documents',
            field=models.FileField(blank=True, help_text='Upload all documents as a single ZIP/PDF or multiple files', null=True, upload_to='doctor_profiles/documents/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='assigned_ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='documents',
            field=djongo.models.fields.JSONField(blank=True, default=dict, help_text='Store all documents in one JSON field:\n    {\n        "qualification_certificate": "file_path_or_url",\n        "nursing_license": "file_path_or_url",\n        "id_proof": "file_path_or_url",\n        "address_proof": "file_path_or_url",\n        "experience_letter": "file_path_or_url",\n        "training_certificates": ["file1.pdf", "file2.pdf"],\n        "other_documents": ["file1.jpg", "file2.pdf"]\n    }\n    '),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='employment_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='shift',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='skills',
            field=djongo.models.fields.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='supervisor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='uploaded_documents',
            field=models.FileField(blank=True, help_text='Upload all documents as a single ZIP/PDF or multiple files', null=True, upload_to='nurse_profiles/documents/'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('recovered', 'Recovered')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
