# Generated by Django 3.2.25 on 2026-04-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20260427_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=500000, null=True),
        ),
    ]
