# Generated by Django 3.2.25 on 2026-06-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20260430_1114'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['email', 'is_verified'], name='accounts_ot_email_45a059_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['expires_at'], name='accounts_ot_expires_b7415d_idx'),
        ),
    ]
