# Generated by Django 3.2.25 on 2026-06-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20260611_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='state_of_licensure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='state_of_licensure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='death_cause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='death_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='discontinuation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='discontinuation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='discontinuation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='recovery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='recovery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='status_reason',
            field=models.CharField(blank=True, choices=[('recovered', 'Recovered - Successfully completed treatment'), ('deceased', 'Deceased - Patient expired'), ('discontinued', 'Discontinued Treatment - Left against medical advice')], max_length=20, null=True),
        ),
    ]
