# Generated by Django 3.2.25 on 2026-06-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20260611_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='death_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='death_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='discontinuation_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='discontinuation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='recovery_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
