# Generated by Django 3.2.25 on 2026-06-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20260611_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='uploaded_documents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='uploaded_documents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
