# Generated by Django 3.2.25 on 2026-02-27 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('dashboard_type', models.CharField(choices=[('NURSE', 'Nurse Dashboard'), ('DOCTOR', 'Doctor Dashboard'), ('ADMIN', 'Admin Dashboard')], max_length=10)),
                ('layout_config', djongo.models.fields.JSONField(default=dict)),
                ('widget_visibility', djongo.models.fields.JSONField(default=dict)),
                ('refresh_interval', models.IntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_preferences',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('PATIENT_TRENDS', 'Patient Response Trends'), ('ALERT_SUMMARY', 'Alert Summary'), ('COMPLETION_RATE', 'Monitoring Completion Rate'), ('RISK_ANALYSIS', 'Risk Analysis'), ('PATIENT_ENGAGEMENT', 'Patient Engagement')], max_length=30)),
                ('parameters', djongo.models.fields.JSONField(default=dict)),
                ('data', djongo.models.fields.JSONField(default=dict)),
                ('file', models.CharField(blank=True, max_length=500, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.adminprofile')),
            ],
            options={
                'db_table': 'analytics_reports',
            },
        ),
        migrations.CreateModel(
            name='PatientAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.adminprofile')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='accounts.doctorprofile')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='accounts.nurseprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='patients.patientmedicalrecord')),
            ],
            options={
                'db_table': 'patient_assignments',
                'unique_together': {('nurse', 'patient')},
            },
        ),
    ]
