# Generated by Django 5.2.12 on 2026-03-11 10:02

import django.db.models.deletion
import djongo.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_voicemessage_voicequestiontemplate'),
        ('notifications', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_method', models.CharField(choices=[('WEBSOCKET', 'WebSocket'), ('PUSH', 'Push Notification'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('IN_APP', 'In-App')], max_length=20)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_deliveries',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('enable_websocket', models.BooleanField(default=True)),
                ('enable_push', models.BooleanField(default=False)),
                ('enable_email', models.BooleanField(default=True)),
                ('enable_sms', models.BooleanField(default=False)),
                ('notification_types', djongo.models.fields.JSONField(default=list)),
                ('priority_threshold', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='LOW', max_length=10)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('quiet_hours_timezone', models.CharField(default='UTC', max_length=50)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('sound_file', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivered_via_websocket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=djongo.models.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='websocket_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='websocket_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('QUESTIONNAIRE', 'Questionnaire Reminder'), ('MEDICATION', 'Medication Reminder'), ('ALERT', 'Alert Notification'), ('MESSAGE', 'Message from Nurse'), ('SYSTEM', 'System Notification'), ('APPOINTMENT', 'Appointment Reminder'), ('VACCINATION', 'Vaccination Update')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notificatio_priorit_17ee5f_idx'),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['notification', 'delivery_method'], name='notificatio_notific_dca583_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status'], name='notificatio_status_ab0dcc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user',)},
        ),
    ]
