# Generated by Django 3.2.25 on 2026-02-27 12:05

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerType',
            fields=[
                ('cancer_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('common_symptoms', djongo.models.fields.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cancer_types',
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalRecord',
            fields=[
                ('medical_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('cancer_stage', models.CharField(choices=[('STAGE_0', 'Stage 0'), ('STAGE_1', 'Stage I'), ('STAGE_2', 'Stage II'), ('STAGE_3', 'Stage III'), ('STAGE_4', 'Stage IV')], max_length=10)),
                ('diagnosis_date', models.DateField()),
                ('hospital_name', models.CharField(max_length=300)),
                ('known_symptoms', models.TextField()),
                ('allergies', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.cancertype')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='accounts.patientprofile')),
                ('treating_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='accounts.doctorprofile')),
            ],
            options={
                'db_table': 'patient_medical_records',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatment_id', models.AutoField(primary_key=True, serialize=False)),
                ('treatment_type', models.CharField(choices=[('CHEMO', 'Chemotherapy'), ('RADIATION', 'Radiation Therapy'), ('SURGERY', 'Surgery'), ('IMMUNO', 'Immunotherapy'), ('HORMONE', 'Hormone Therapy'), ('TARGETED', 'Targeted Therapy'), ('OTHER', 'Other')], max_length=20)),
                ('treatment_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused')], default='PLANNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='patients.patientmedicalrecord')),
            ],
            options={
                'db_table': 'treatments',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.AutoField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('ONCE', 'Once daily'), ('TWICE', 'Twice daily'), ('THRICE', 'Thrice daily'), ('FOUR', 'Four times daily'), ('AS_NEEDED', 'As needed')], max_length=20)),
                ('timing', djongo.models.fields.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patientmedicalrecord')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.doctorprofile')),
            ],
            options={
                'db_table': 'medications',
            },
        ),
    ]
