# Generated by Django 3.2.25 on 2026-03-17 11:02

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'food_categories',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('food_type', models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('VEGAN', 'Vegan'), ('EGG', 'Eggitarian')], default='VEG', max_length=20)),
                ('nutritional_info', djongo.models.fields.JSONField(default=dict)),
                ('common_allergen', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_items', to='patients.foodcategory')),
            ],
            options={
                'db_table': 'food_items',
            },
        ),
        migrations.CreateModel(
            name='PatientFoodLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack'), ('SUPPLEMENT', 'Supplement')], max_length=20)),
                ('quantity_consumed', models.CharField(max_length=100)),
                ('consumed_at', models.DateTimeField()),
                ('symptoms_experienced', models.TextField(blank=True)),
                ('symptom_severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.fooditem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'patient_food_logs',
                'ordering': ['-consumed_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientDietaryPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack'), ('SUPPLEMENT', 'Supplement')], max_length=20)),
                ('quantity', models.CharField(max_length=100)),
                ('timing', models.TimeField(blank=True, null=True)),
                ('frequency', models.CharField(default='Daily', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescribed_diets', to='accounts.doctorprofile')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.fooditem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_plans', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'patient_dietary_plans',
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('meal_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('weekday', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('ALL', 'All Days')], default='ALL', max_length=20)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack'), ('SUPPLEMENT', 'Supplement')], max_length=20)),
                ('food_items', djongo.models.fields.JSONField(default=list)),
                ('total_calories', models.IntegerField(blank=True, null=True)),
                ('total_protein', models.FloatField(blank=True, null=True)),
                ('total_carbs', models.FloatField(blank=True, null=True)),
                ('total_fat', models.FloatField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'meal_plans',
            },
        ),
        migrations.CreateModel(
            name='DietaryRestriction',
            fields=[
                ('restriction_id', models.AutoField(primary_key=True, serialize=False)),
                ('restriction_type', models.CharField(choices=[('ALLERGY', 'Allergy'), ('INTOLERANCE', 'Intolerance'), ('RELIGIOUS', 'Religious'), ('TREATMENT_RELATED', 'Treatment Related'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(blank=True, max_length=50)),
                ('diagnosed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.foodcategory')),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.fooditem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_restrictions', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'dietary_restrictions',
            },
        ),
        migrations.CreateModel(
            name='DietaryRecommendation',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('RECOMMENDED', 'Recommended'), ('AVOID', 'Avoid'), ('CAUTION', 'Caution'), ('LIMIT', 'Limit Intake')], max_length=20)),
                ('applicable_stages', djongo.models.fields.JSONField(default=list)),
                ('reason', models.TextField()),
                ('scientific_evidence', models.TextField(blank=True)),
                ('preparation_method', models.TextField(blank=True)),
                ('alternatives', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_recommendations', to='patients.cancertype')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='patients.fooditem')),
            ],
            options={
                'db_table': 'dietary_recommendations',
                'unique_together': {('cancer_type', 'food_item', 'recommendation_type')},
            },
        ),
    ]
