# Generated by Django 3.2.25 on 2026-03-30 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patientprofile_patient_no'),
        ('patients', '0002_dietaryrecommendation_dietaryrestriction_foodcategory_fooditem_mealplan_patientdietaryplan_patientfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicalrecord',
            name='assigned_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='accounts.nurseprofile'),
        ),
    ]
