# Generated by Django 3.2.25 on 2026-06-11 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20260611_1710'),
        ('patients', '0003_patientmedicalrecord_assigned_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='accounts.patientprofile'),
        ),
    ]
