# Generated by Django 3.2.25 on 2026-09-01 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_phone_number'),
        ('patients', '0004_alter_patientmedicalrecord_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientmedicalrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='patientmedicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='accounts.patientprofile'),
        ),
    ]
