# Generated by Django 3.2.25 on 2026-02-27 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaires', '0001_initial'),
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated')], default='NEW', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('trigger_conditions', djongo.models.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to_nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_alerts', to='accounts.nurseprofile')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_date', models.DateField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_responses', to='patients.patientmedicalrecord')),
                ('questionnaire_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaires.questionnaireassignment')),
            ],
            options={
                'db_table': 'daily_responses',
                'unique_together': {('patient', 'response_date', 'questionnaire_assignment')},
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('question_response_id', models.AutoField(primary_key=True, serialize=False)),
                ('yes_no_response', models.BooleanField(blank=True, null=True)),
                ('multiple_choice_response', models.CharField(blank=True, max_length=200)),
                ('scale_response', models.IntegerField(blank=True, null=True)),
                ('text_response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaires.assignedquestion')),
                ('daily_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='monitoring.dailyresponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaires.question')),
            ],
            options={
                'db_table': 'question_responses',
            },
        ),
        migrations.CreateModel(
            name='PatientNote',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='monitoring.alert')),
                ('author_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.doctorprofile')),
                ('author_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.nurseprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='patients.patientmedicalrecord')),
            ],
            options={
                'db_table': 'patient_notes',
            },
        ),
        migrations.CreateModel(
            name='AlertEscalation',
            fields=[
                ('escalation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='monitoring.alert')),
                ('escalated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.nurseprofile')),
                ('escalated_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.doctorprofile')),
            ],
            options={
                'db_table': 'alert_escalations',
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='daily_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.dailyresponse'),
        ),
        migrations.AddField(
            model_name='alert',
            name='escalated_to_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalated_alerts', to='accounts.doctorprofile'),
        ),
        migrations.AddField(
            model_name='alert',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.patientmedicalrecord'),
        ),
        migrations.AddField(
            model_name='alert',
            name='related_responses',
            field=models.ManyToManyField(blank=True, to='monitoring.QuestionResponse'),
        ),
    ]
