# Generated by Django 3.2.25 on 2026-03-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
        ('patients', '0001_initial'),
        ('accounts', '0002_alter_user_phone_number'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceQuestionTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('text_content', models.TextField()),
                ('tamil_content', models.TextField(blank=True)),
                ('english_voice', models.FileField(blank=True, null=True, upload_to='voice_templates/english/')),
                ('tamil_voice', models.FileField(blank=True, null=True, upload_to='voice_templates/tamil/')),
                ('duration', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaires.question')),
            ],
            options={
                'db_table': 'voice_question_templates',
            },
        ),
        migrations.CreateModel(
            name='VoiceMessage',
            fields=[
                ('voice_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('QUESTION', 'Question from Nurse'), ('REPLY', 'Reply from Patient'), ('ALERT', 'Alert Notification')], default='QUESTION', max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('REPLIED', 'Replied')], default='SENT', max_length=20)),
                ('voice_file', models.FileField(blank=True, null=True, upload_to='voice_messages/%Y/%m/%d/')),
                ('voice_duration', models.IntegerField(default=0)),
                ('voice_text', models.TextField(blank=True)),
                ('tamil_text', models.TextField(blank=True)),
                ('tamil_voice_file', models.FileField(blank=True, null=True, upload_to='voice_messages/tamil/%Y/%m/%d/')),
                ('is_urgent', models.BooleanField(default=False)),
                ('requires_response', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_messages', to='monitoring.alert')),
                ('daily_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_messages', to='monitoring.dailyresponse')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_voice_messages', to='accounts.doctorprofile')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_voice_messages', to='accounts.nurseprofile')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='monitoring.voicemessage')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_messages', to='patients.patientmedicalrecord')),
            ],
            options={
                'db_table': 'voice_messages',
                'ordering': ['-sent_at'],
            },
        ),
    ]
