# Generated by Django 3.2.25 on 2026-02-27 12:05

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'question_categories',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Twice a week'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.nurseprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_assignments', to='patients.patientmedicalrecord')),
            ],
            options={
                'db_table': 'questionnaire_assignments',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('YES_NO', 'Yes/No'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('SCALE', 'Scale (1-10)'), ('TEXT', 'Text Input')], max_length=20)),
                ('options', djongo.models.fields.JSONField(default=list)),
                ('scale_min', models.IntegerField(default=1)),
                ('scale_max', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('default_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Twice a week'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=20)),
                ('help_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questionnaires.questioncategory')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='AssignedQuestion',
            fields=[
                ('assigned_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('conditional_answer', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conditional_on_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditional_questions', to='questionnaires.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.question')),
                ('questionnaire_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_questions', to='questionnaires.questionnaireassignment')),
            ],
            options={
                'db_table': 'assigned_questions',
                'ordering': ['order'],
            },
        ),
    ]
